# -*- coding: utf-8 -*-
"""k-MEANS-SCRATCH-PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vzKSCk_-1iVH8VM2JhFXhZ4Hkdaw1df
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.metrics import silhouette_score

np.random.seed(42)

# -------- Dataset Generation --------
X, _ = make_blobs(
    n_samples=600,
    centers=5,
    cluster_std=[1.0,1.3,0.8,1.2,1.0],
    n_features=2
)

# -------- K-Means From Scratch --------
class KMeansScratch:
    def __init__(self, k, max_iters=100):
        self.k = k
        self.max_iters = max_iters

    def initialize_centroids(self, X):
        idx = np.random.choice(len(X), self.k, replace=False)
        return X[idx]

    def compute_distances(self, X, centroids):
        return np.array([np.linalg.norm(X - c, axis=1) for c in centroids]).T

    def assign_clusters(self, distances):
        return np.argmin(distances, axis=1)

    def update_centroids(self, X, labels):
        return np.array([X[labels == i].mean(axis=0) for i in range(self.k)])

    def fit(self, X):
        self.centroids = self.initialize_centroids(X)

        for i in range(self.max_iters):
            distances = self.compute_distances(X, self.centroids)
            labels = self.assign_clusters(distances)
            new_centroids = self.update_centroids(X, labels)

            if np.allclose(self.centroids, new_centroids):
                print(f"Converged at iteration {i}")
                break

            self.centroids = new_centroids

        return labels

# -------- Optimal K Selection --------
scores = []
K_range = range(2,11)

for k in K_range:
    model = KMeansScratch(k)
    labels = model.fit(X)
    score = silhouette_score(X, labels)
    scores.append(score)
    print(f"K={k} -> Silhouette Score={score:.4f}")

optimal_k = K_range[np.argmax(scores)]
print("\nOptimal K:", optimal_k)

# -------- Final Clustering --------
final_model = KMeansScratch(optimal_k)
final_labels = final_model.fit(X)
centroids = final_model.centroids

# -------- Visualization --------
plt.figure(figsize=(8,6))

for i in range(optimal_k):
    plt.scatter(
        X[final_labels==i][:,0],
        X[final_labels==i][:,1],
        label=f"Cluster {i+1}"
    )

plt.scatter(
    centroids[:,0], centroids[:,1],
    c="black", s=200, marker="X", label="Centroids"
)

plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("K-Means Clustering From Scratch")
plt.legend()
plt.show()

